[workspace]

members = [ 
    "appbiotic/code/error",
]

resolver = "2"

[package]
name = "appbiotic"
version = "0.1.2"
edition = "2021"
authors = [
    "Kristopher Wuollett <kris@appbiotic.com>",
]
license = "MIT"
description = "Tools to package to build services that can be managed similarly."
homepage = "https://appbiotic.com/"
repository = "https://github.com/appbiotic/code/"
readme = "README.md"
include = [
    "src/**/*.rs",
    "Cargo.lock",
    "Cargo.toml",
    "LICENSE",
    "NOTICE",
    "README.md",
]

# TODO: Find or create tool to propagte orthogonal `with-*` features.
[features]
full = [
    "with-grpc",
]
with-grpc = [
    "appbiotic-code-error/with-grpc",
]

[dependencies]
appbiotic-code-error = { version = "0.1.2", path = "appbiotic/code/error", default-features = false}
