[workspace]

members = [ 
    "appbiotic/code/error",
]

resolver = "2"

[package]
name = "appbiotic"
version = "0.1.0"
edition = "2021"
authors = [
    "Kristopher Wuollett <kris@appbiotic.com>",
]
license-file = "LICENSE"
description = "Tools to package to build services that can be managed similarly."
homepage = "https://appbiotic.com/"
repository = "https://github.com/appbiotic/code/"
readme = "README.md"
publish-lockfile = true
include = [
    "src/**/*.rs",
    "Cargo.lock",
    "Cargo.toml",
    "LICENSE",
    "NOTICE",
    "README.md",
]

[dependencies]
appbiotic-code-error = { version = "0.1.0", path = "appbiotic/code/error", default-features = false}
