[package]
name = "appbiotic-code-error"
version = "0.1.1"
edition = "2021"
authors = [
    "Kristopher Wuollett <kris@appbiotic.com>",
]
license = "Apache-2.0"
description = "A set of error types to build services that can be managed similarly."
homepage = "https://appbiotic.com/"
repository = "https://github.com/appbiotic/code/"
readme = "README.md"
publish-lockfile = true

[dependencies]
strum = "0.25"
strum_macros = "0.25"
thiserror = "1.0.48"
