[package]
name = "appbiotic-code-error"
version = "0.1.3"
edition = "2021"
authors = [
    "Kristopher Wuollett <kris@appbiotic.com>",
]
license = "Apache-2.0"
description = "A set of error types to build services that can be managed similarly."
homepage = "https://appbiotic.com/"
repository = "https://github.com/appbiotic/code/"
readme = "README.md"

[features]
with-grpc = []
with-http = ["dep:http"]
with-tonic = ["dep:tonic"]

[dependencies]
http = { version = "0.2.9", optional = true, default-features = false }
strum = "0.25"
strum_macros = "0.25"
thiserror = "1.0.48"
tonic = { version = "0.10.0", optional = true, default-features = false }
