language = "C"

include_guard = "APPBIOTIC_CODE_ERROR"
includes = ["appbiotic/code/ffi/ffi.h"]
# TODO: Only include core foundation for apple builds
sys_includes = ["CoreFoundation/CoreFoundation.h"]

[enum]
prefix_with_name = true

[export]
include = ["AppbioticCodeError_ResultCallback"]
