
[package]
name = "appbiotic-code-cli"
version = "0.3.0"
edition = "2021"

[features]
default = ["with-examples-greeter"]
with-examples = ["appbiotic-examples/with-cli-cmd"]
with-examples-greeter = ["with-examples", "appbiotic-examples/with-greeter"]

[dependencies]
appbiotic-code-runtime = { workspace = true }
appbiotic-examples = { workspace = true, optional = true }
clap = { workspace = true, features = ["derive", "std"] }
tracing = { workspace = true }
