
[package]
name = "appbiotic-code-cli"
version = "0.1.4"
edition = "2021"

[features]
default = ["with-examples-greeter"]
with-examples-greeter = ["with-examples", "appbiotic-examples/with-greeter"]
with-examples = ["appbiotic-examples/with-cli-cmd"]

[dependencies]
appbiotic-code-runtime = { version = "0.1.0", path = "../runtime", default-features = false }
appbiotic-examples = { version = "0.1.0", path = "../../examples", default-features = false, optional = true }
clap = { version = "4.4.2", features = ["derive"] }
tracing = "0.1.37"
