
[package]
name = "appbiotic-code-cli"
version = "0.1.4"
edition = "2021"

[features]
default = ["with-examples-greeter"]
with-examples-greeter = [
    "with-examples",
    "appbiotic-examples-cli-cmd/with-greeter",
]
with-examples = []

[dependencies]
appbiotic-examples-cli-cmd = { version = "0.1.0", path = "../../examples/cli-cmd", default-features = false, optional = true }
clap = { version = "4.4.2", features = ["derive"] }
