[package]
name = "appbiotic-examples"
version = "0.3.0"
edition = "2021"

[features]
with-cli-cmd = ["dep:clap", "clap/derive"]
with-greeter = []

[dependencies]
appbiotic-code-error = { workspace = true }
clap = { workspace = true, optional = true }
