[package]
name = "appbiotic-code-runtime"
version = "0.3.0-alpha.0"
edition = "2021"

[dependencies]
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }
