[package]
name = "appbiotic-code-ffi"
version = "0.3.0-alpha.1"
edition = "2021"

[features]
full = ["json", "protos"]
json = []
protos = []

[dependencies]
tracing = { workspace = true }

[build-dependencies]
cbindgen = { workspace = true }
